> npm install --global yarn

> yarn init
> yarn add babel-preset-react
> yarn add babel-preset-env
> yarn add live-server babel-cli@6.24.1
> yarn add webpack@3.1.0

> yarn run build
> yarn run serve

/* to remove global config */
// using yarn
> yarn global remove babel-cli live-server

// using npm
> npm uninstall -g babel-cli live-server

-----------------------------
All possible React DOM elements --> https://reactjs.org/docs/dom-elements.html
Webpack webpage --> https://webpack.js.org
